include: default_af.yaml
task: truthfulqa_zh_mubench
dataset_name: TruthfulQADataset_lighteval_zh
doc_to_text: !function pinyin_abbreviation.mubench_doc_to_text
doc_to_choice: !function pinyin_abbreviation.mubench_doc_to_choice
