include: default_af.yaml
task: xstorycloze_zh_mubench
dataset_name: StoryClozeDataset_lighteval_zh
doc_to_text: !function tasks.pinyin_abbreviation.mubench_doc_to_text
doc_to_choice: !function tasks.pinyin_abbreviation.mubench_doc_to_choice
